### ISSUE TITLE
Link to article explaining this hack

### ISSUE THREAD

**Issue by SeeThruHead** [postcss/postcss-will-change#1]
Can the readme get a link to what this 3d hack does. Or maybe explain it in the readme? Having trouble googling it.

**Comment by TrySound** [comment]
@SeeThruHead  Did you read about `will-change` css property?

**Comment by SeeThruHead** [comment]
Yes.

**Comment by TrySound** [comment]
@SeeThruHead `transform: translate3d(0, 0, 0)` uses for the same thing, but it is hack. `backface-visibility: hidden` the same hack but:
> This plugin uses backface-visibility to has prevent overriding more popular transform property.

**Comment by SeeThruHead** [comment]
That is what I thought it did, but I was unclear, and googling did not turn up something I could rely upon.

So, this hack promotes a selector to GPU rendering if the browser does not support will-change correct?

**Comment by ai** [comment]
@SeeThruHead https://dev.opera.com/articles/css-will-change-property/

**Comment by SeeThruHead** [comment]
@ai That article makes no mention of backface-visibility.

**Comment by ai** [comment]
Done be36588

**Comment by ai** [comment]
@SeeThruHead any 3D property will create a new layout. So `backface-visibility` is equal to `translateZ(0)` or `translate3d(0, 0, 0)`. But `transform` property often used, so using it in this plugin will create more side effects.

**Comment by SeeThruHead** [comment]
I understand, that information is what i think should be included in the readme. Backface-visibility as an alternative to translate3d is not something someone knows inherently.

**Comment by ai** [comment]
What else we can add to this text from `README.md`?

> This plugin uses `backface-visibility` to has prevent overriding more popular `transform` property.
