### ISSUE TITLE
Support `postcss@7`

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss-will-change#5]

**Comment by ai** [comment]
PostCSS 7 has no API changes. So it is ok to not update plugins.

Or do you have some error?

**Comment by evilebottnawi** [comment]
@ai just avoid install `postcss@6` (decrease `node_modules`)

**Comment by ai** [comment]
Good reason. Well update plugins after NEJS talk (July 27)

**Comment by evilebottnawi** [comment]
@ai I will send a PR if find time early

**Comment by ai** [comment]
Update also require changing code style according new PostCSS ESLint config and moving to clean-publish to trim dev configs from npm’s package.json.

**Comment by kaelig** [comment]
Hi there! Any updates on this support task?

**Comment by ai** [comment]
I will try to release all my plugins with Babel 7 on next week

**Comment by ai** [comment]
Done https://github.com/postcss/postcss-will-change/commit/12adb6bf8083e3c6e6230819d8e4e162970ebcb4

Released in 3.0
